/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechRouteImport } from './routes/tech'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as TechIndexRouteImport } from './routes/tech.index'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as TechCamionRouteImport } from './routes/tech.camion'
import { Route as AppTresorerieRouteImport } from './routes/_app.tresorerie'
import { Route as AppStatsRouteImport } from './routes/_app.stats'
import { Route as AppPlanningRouteImport } from './routes/_app.planning'
import { Route as AppParametresRouteImport } from './routes/_app.parametres'
import { Route as AppOnboardingRouteImport } from './routes/_app.onboarding'
import { Route as AppAnalytiqueRouteImport } from './routes/_app.analytique'
import { Route as TechInterventionsIndexRouteImport } from './routes/tech.interventions.index'
import { Route as AppVehiculesIndexRouteImport } from './routes/_app.vehicules.index'
import { Route as AppStockIndexRouteImport } from './routes/_app.stock.index'
import { Route as AppReapproIndexRouteImport } from './routes/_app.reappro.index'
import { Route as AppInterventionsIndexRouteImport } from './routes/_app.interventions.index'
import { Route as AppFacturesIndexRouteImport } from './routes/_app.factures.index'
import { Route as AppEquipeIndexRouteImport } from './routes/_app.equipe.index'
import { Route as AppDevisIndexRouteImport } from './routes/_app.devis.index'
import { Route as AppClientsIndexRouteImport } from './routes/_app.clients.index'
import { Route as TechInterventionsIdRouteImport } from './routes/tech.interventions.$id'
import { Route as AppInterventionsNewRouteImport } from './routes/_app.interventions.new'
import { Route as AppInterventionsIdRouteImport } from './routes/_app.interventions.$id'
import { Route as AppFacturesNewRouteImport } from './routes/_app.factures.new'
import { Route as AppFacturesIdRouteImport } from './routes/_app.factures.$id'
import { Route as AppDevisNewRouteImport } from './routes/_app.devis.new'
import { Route as AppDevisIdRouteImport } from './routes/_app.devis.$id'
import { Route as AppClientsNewRouteImport } from './routes/_app.clients.new'
import { Route as AppClientsIdRouteImport } from './routes/_app.clients.$id'

const TechRoute = TechRouteImport.update({
  id: '/tech',
  path: '/tech',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const TechIndexRoute = TechIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TechRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const TechCamionRoute = TechCamionRouteImport.update({
  id: '/camion',
  path: '/camion',
  getParentRoute: () => TechRoute,
} as any)
const AppTresorerieRoute = AppTresorerieRouteImport.update({
  id: '/tresorerie',
  path: '/tresorerie',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanningRoute = AppPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => AppRoute,
} as any)
const AppParametresRoute = AppParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalytiqueRoute = AppAnalytiqueRouteImport.update({
  id: '/analytique',
  path: '/analytique',
  getParentRoute: () => AppRoute,
} as any)
const TechInterventionsIndexRoute = TechInterventionsIndexRouteImport.update({
  id: '/interventions/',
  path: '/interventions/',
  getParentRoute: () => TechRoute,
} as any)
const AppVehiculesIndexRoute = AppVehiculesIndexRouteImport.update({
  id: '/vehicules/',
  path: '/vehicules/',
  getParentRoute: () => AppRoute,
} as any)
const AppStockIndexRoute = AppStockIndexRouteImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => AppRoute,
} as any)
const AppReapproIndexRoute = AppReapproIndexRouteImport.update({
  id: '/reappro/',
  path: '/reappro/',
  getParentRoute: () => AppRoute,
} as any)
const AppInterventionsIndexRoute = AppInterventionsIndexRouteImport.update({
  id: '/interventions/',
  path: '/interventions/',
  getParentRoute: () => AppRoute,
} as any)
const AppFacturesIndexRoute = AppFacturesIndexRouteImport.update({
  id: '/factures/',
  path: '/factures/',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipeIndexRoute = AppEquipeIndexRouteImport.update({
  id: '/equipe/',
  path: '/equipe/',
  getParentRoute: () => AppRoute,
} as any)
const AppDevisIndexRoute = AppDevisIndexRouteImport.update({
  id: '/devis/',
  path: '/devis/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppRoute,
} as any)
const TechInterventionsIdRoute = TechInterventionsIdRouteImport.update({
  id: '/interventions/$id',
  path: '/interventions/$id',
  getParentRoute: () => TechRoute,
} as any)
const AppInterventionsNewRoute = AppInterventionsNewRouteImport.update({
  id: '/interventions/new',
  path: '/interventions/new',
  getParentRoute: () => AppRoute,
} as any)
const AppInterventionsIdRoute = AppInterventionsIdRouteImport.update({
  id: '/interventions/$id',
  path: '/interventions/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppFacturesNewRoute = AppFacturesNewRouteImport.update({
  id: '/factures/new',
  path: '/factures/new',
  getParentRoute: () => AppRoute,
} as any)
const AppFacturesIdRoute = AppFacturesIdRouteImport.update({
  id: '/factures/$id',
  path: '/factures/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDevisNewRoute = AppDevisNewRouteImport.update({
  id: '/devis/new',
  path: '/devis/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDevisIdRoute = AppDevisIdRouteImport.update({
  id: '/devis/$id',
  path: '/devis/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsNewRoute = AppClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIdRoute = AppClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/tech': typeof TechRouteWithChildren
  '/analytique': typeof AppAnalytiqueRoute
  '/onboarding': typeof AppOnboardingRoute
  '/parametres': typeof AppParametresRoute
  '/planning': typeof AppPlanningRoute
  '/stats': typeof AppStatsRoute
  '/tresorerie': typeof AppTresorerieRoute
  '/tech/camion': typeof TechCamionRoute
  '/tech/': typeof TechIndexRoute
  '/clients/$id': typeof AppClientsIdRoute
  '/clients/new': typeof AppClientsNewRoute
  '/devis/$id': typeof AppDevisIdRoute
  '/devis/new': typeof AppDevisNewRoute
  '/factures/$id': typeof AppFacturesIdRoute
  '/factures/new': typeof AppFacturesNewRoute
  '/interventions/$id': typeof AppInterventionsIdRoute
  '/interventions/new': typeof AppInterventionsNewRoute
  '/tech/interventions/$id': typeof TechInterventionsIdRoute
  '/clients/': typeof AppClientsIndexRoute
  '/devis/': typeof AppDevisIndexRoute
  '/equipe/': typeof AppEquipeIndexRoute
  '/factures/': typeof AppFacturesIndexRoute
  '/interventions/': typeof AppInterventionsIndexRoute
  '/reappro/': typeof AppReapproIndexRoute
  '/stock/': typeof AppStockIndexRoute
  '/vehicules/': typeof AppVehiculesIndexRoute
  '/tech/interventions/': typeof TechInterventionsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/analytique': typeof AppAnalytiqueRoute
  '/onboarding': typeof AppOnboardingRoute
  '/parametres': typeof AppParametresRoute
  '/planning': typeof AppPlanningRoute
  '/stats': typeof AppStatsRoute
  '/tresorerie': typeof AppTresorerieRoute
  '/tech/camion': typeof TechCamionRoute
  '/': typeof AppIndexRoute
  '/tech': typeof TechIndexRoute
  '/clients/$id': typeof AppClientsIdRoute
  '/clients/new': typeof AppClientsNewRoute
  '/devis/$id': typeof AppDevisIdRoute
  '/devis/new': typeof AppDevisNewRoute
  '/factures/$id': typeof AppFacturesIdRoute
  '/factures/new': typeof AppFacturesNewRoute
  '/interventions/$id': typeof AppInterventionsIdRoute
  '/interventions/new': typeof AppInterventionsNewRoute
  '/tech/interventions/$id': typeof TechInterventionsIdRoute
  '/clients': typeof AppClientsIndexRoute
  '/devis': typeof AppDevisIndexRoute
  '/equipe': typeof AppEquipeIndexRoute
  '/factures': typeof AppFacturesIndexRoute
  '/interventions': typeof AppInterventionsIndexRoute
  '/reappro': typeof AppReapproIndexRoute
  '/stock': typeof AppStockIndexRoute
  '/vehicules': typeof AppVehiculesIndexRoute
  '/tech/interventions': typeof TechInterventionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/tech': typeof TechRouteWithChildren
  '/_app/analytique': typeof AppAnalytiqueRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/parametres': typeof AppParametresRoute
  '/_app/planning': typeof AppPlanningRoute
  '/_app/stats': typeof AppStatsRoute
  '/_app/tresorerie': typeof AppTresorerieRoute
  '/tech/camion': typeof TechCamionRoute
  '/_app/': typeof AppIndexRoute
  '/tech/': typeof TechIndexRoute
  '/_app/clients/$id': typeof AppClientsIdRoute
  '/_app/clients/new': typeof AppClientsNewRoute
  '/_app/devis/$id': typeof AppDevisIdRoute
  '/_app/devis/new': typeof AppDevisNewRoute
  '/_app/factures/$id': typeof AppFacturesIdRoute
  '/_app/factures/new': typeof AppFacturesNewRoute
  '/_app/interventions/$id': typeof AppInterventionsIdRoute
  '/_app/interventions/new': typeof AppInterventionsNewRoute
  '/tech/interventions/$id': typeof TechInterventionsIdRoute
  '/_app/clients/': typeof AppClientsIndexRoute
  '/_app/devis/': typeof AppDevisIndexRoute
  '/_app/equipe/': typeof AppEquipeIndexRoute
  '/_app/factures/': typeof AppFacturesIndexRoute
  '/_app/interventions/': typeof AppInterventionsIndexRoute
  '/_app/reappro/': typeof AppReapproIndexRoute
  '/_app/stock/': typeof AppStockIndexRoute
  '/_app/vehicules/': typeof AppVehiculesIndexRoute
  '/tech/interventions/': typeof TechInterventionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/tech'
    | '/analytique'
    | '/onboarding'
    | '/parametres'
    | '/planning'
    | '/stats'
    | '/tresorerie'
    | '/tech/camion'
    | '/tech/'
    | '/clients/$id'
    | '/clients/new'
    | '/devis/$id'
    | '/devis/new'
    | '/factures/$id'
    | '/factures/new'
    | '/interventions/$id'
    | '/interventions/new'
    | '/tech/interventions/$id'
    | '/clients/'
    | '/devis/'
    | '/equipe/'
    | '/factures/'
    | '/interventions/'
    | '/reappro/'
    | '/stock/'
    | '/vehicules/'
    | '/tech/interventions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/analytique'
    | '/onboarding'
    | '/parametres'
    | '/planning'
    | '/stats'
    | '/tresorerie'
    | '/tech/camion'
    | '/'
    | '/tech'
    | '/clients/$id'
    | '/clients/new'
    | '/devis/$id'
    | '/devis/new'
    | '/factures/$id'
    | '/factures/new'
    | '/interventions/$id'
    | '/interventions/new'
    | '/tech/interventions/$id'
    | '/clients'
    | '/devis'
    | '/equipe'
    | '/factures'
    | '/interventions'
    | '/reappro'
    | '/stock'
    | '/vehicules'
    | '/tech/interventions'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/tech'
    | '/_app/analytique'
    | '/_app/onboarding'
    | '/_app/parametres'
    | '/_app/planning'
    | '/_app/stats'
    | '/_app/tresorerie'
    | '/tech/camion'
    | '/_app/'
    | '/tech/'
    | '/_app/clients/$id'
    | '/_app/clients/new'
    | '/_app/devis/$id'
    | '/_app/devis/new'
    | '/_app/factures/$id'
    | '/_app/factures/new'
    | '/_app/interventions/$id'
    | '/_app/interventions/new'
    | '/tech/interventions/$id'
    | '/_app/clients/'
    | '/_app/devis/'
    | '/_app/equipe/'
    | '/_app/factures/'
    | '/_app/interventions/'
    | '/_app/reappro/'
    | '/_app/stock/'
    | '/_app/vehicules/'
    | '/tech/interventions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  TechRoute: typeof TechRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tech': {
      id: '/tech'
      path: '/tech'
      fullPath: '/tech'
      preLoaderRoute: typeof TechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech/': {
      id: '/tech/'
      path: '/'
      fullPath: '/tech/'
      preLoaderRoute: typeof TechIndexRouteImport
      parentRoute: typeof TechRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/tech/camion': {
      id: '/tech/camion'
      path: '/camion'
      fullPath: '/tech/camion'
      preLoaderRoute: typeof TechCamionRouteImport
      parentRoute: typeof TechRoute
    }
    '/_app/tresorerie': {
      id: '/_app/tresorerie'
      path: '/tresorerie'
      fullPath: '/tresorerie'
      preLoaderRoute: typeof AppTresorerieRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stats': {
      id: '/_app/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planning': {
      id: '/_app/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof AppPlanningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parametres': {
      id: '/_app/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AppParametresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytique': {
      id: '/_app/analytique'
      path: '/analytique'
      fullPath: '/analytique'
      preLoaderRoute: typeof AppAnalytiqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/tech/interventions/': {
      id: '/tech/interventions/'
      path: '/interventions'
      fullPath: '/tech/interventions/'
      preLoaderRoute: typeof TechInterventionsIndexRouteImport
      parentRoute: typeof TechRoute
    }
    '/_app/vehicules/': {
      id: '/_app/vehicules/'
      path: '/vehicules'
      fullPath: '/vehicules/'
      preLoaderRoute: typeof AppVehiculesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock/': {
      id: '/_app/stock/'
      path: '/stock'
      fullPath: '/stock/'
      preLoaderRoute: typeof AppStockIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reappro/': {
      id: '/_app/reappro/'
      path: '/reappro'
      fullPath: '/reappro/'
      preLoaderRoute: typeof AppReapproIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interventions/': {
      id: '/_app/interventions/'
      path: '/interventions'
      fullPath: '/interventions/'
      preLoaderRoute: typeof AppInterventionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/factures/': {
      id: '/_app/factures/'
      path: '/factures'
      fullPath: '/factures/'
      preLoaderRoute: typeof AppFacturesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipe/': {
      id: '/_app/equipe/'
      path: '/equipe'
      fullPath: '/equipe/'
      preLoaderRoute: typeof AppEquipeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devis/': {
      id: '/_app/devis/'
      path: '/devis'
      fullPath: '/devis/'
      preLoaderRoute: typeof AppDevisIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/': {
      id: '/_app/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/tech/interventions/$id': {
      id: '/tech/interventions/$id'
      path: '/interventions/$id'
      fullPath: '/tech/interventions/$id'
      preLoaderRoute: typeof TechInterventionsIdRouteImport
      parentRoute: typeof TechRoute
    }
    '/_app/interventions/new': {
      id: '/_app/interventions/new'
      path: '/interventions/new'
      fullPath: '/interventions/new'
      preLoaderRoute: typeof AppInterventionsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interventions/$id': {
      id: '/_app/interventions/$id'
      path: '/interventions/$id'
      fullPath: '/interventions/$id'
      preLoaderRoute: typeof AppInterventionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/factures/new': {
      id: '/_app/factures/new'
      path: '/factures/new'
      fullPath: '/factures/new'
      preLoaderRoute: typeof AppFacturesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/factures/$id': {
      id: '/_app/factures/$id'
      path: '/factures/$id'
      fullPath: '/factures/$id'
      preLoaderRoute: typeof AppFacturesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devis/new': {
      id: '/_app/devis/new'
      path: '/devis/new'
      fullPath: '/devis/new'
      preLoaderRoute: typeof AppDevisNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devis/$id': {
      id: '/_app/devis/$id'
      path: '/devis/$id'
      fullPath: '/devis/$id'
      preLoaderRoute: typeof AppDevisIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/new': {
      id: '/_app/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AppClientsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/$id': {
      id: '/_app/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AppClientsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalytiqueRoute: typeof AppAnalytiqueRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppParametresRoute: typeof AppParametresRoute
  AppPlanningRoute: typeof AppPlanningRoute
  AppStatsRoute: typeof AppStatsRoute
  AppTresorerieRoute: typeof AppTresorerieRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClientsIdRoute: typeof AppClientsIdRoute
  AppClientsNewRoute: typeof AppClientsNewRoute
  AppDevisIdRoute: typeof AppDevisIdRoute
  AppDevisNewRoute: typeof AppDevisNewRoute
  AppFacturesIdRoute: typeof AppFacturesIdRoute
  AppFacturesNewRoute: typeof AppFacturesNewRoute
  AppInterventionsIdRoute: typeof AppInterventionsIdRoute
  AppInterventionsNewRoute: typeof AppInterventionsNewRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppDevisIndexRoute: typeof AppDevisIndexRoute
  AppEquipeIndexRoute: typeof AppEquipeIndexRoute
  AppFacturesIndexRoute: typeof AppFacturesIndexRoute
  AppInterventionsIndexRoute: typeof AppInterventionsIndexRoute
  AppReapproIndexRoute: typeof AppReapproIndexRoute
  AppStockIndexRoute: typeof AppStockIndexRoute
  AppVehiculesIndexRoute: typeof AppVehiculesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalytiqueRoute: AppAnalytiqueRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppParametresRoute: AppParametresRoute,
  AppPlanningRoute: AppPlanningRoute,
  AppStatsRoute: AppStatsRoute,
  AppTresorerieRoute: AppTresorerieRoute,
  AppIndexRoute: AppIndexRoute,
  AppClientsIdRoute: AppClientsIdRoute,
  AppClientsNewRoute: AppClientsNewRoute,
  AppDevisIdRoute: AppDevisIdRoute,
  AppDevisNewRoute: AppDevisNewRoute,
  AppFacturesIdRoute: AppFacturesIdRoute,
  AppFacturesNewRoute: AppFacturesNewRoute,
  AppInterventionsIdRoute: AppInterventionsIdRoute,
  AppInterventionsNewRoute: AppInterventionsNewRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppDevisIndexRoute: AppDevisIndexRoute,
  AppEquipeIndexRoute: AppEquipeIndexRoute,
  AppFacturesIndexRoute: AppFacturesIndexRoute,
  AppInterventionsIndexRoute: AppInterventionsIndexRoute,
  AppReapproIndexRoute: AppReapproIndexRoute,
  AppStockIndexRoute: AppStockIndexRoute,
  AppVehiculesIndexRoute: AppVehiculesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface TechRouteChildren {
  TechCamionRoute: typeof TechCamionRoute
  TechIndexRoute: typeof TechIndexRoute
  TechInterventionsIdRoute: typeof TechInterventionsIdRoute
  TechInterventionsIndexRoute: typeof TechInterventionsIndexRoute
}

const TechRouteChildren: TechRouteChildren = {
  TechCamionRoute: TechCamionRoute,
  TechIndexRoute: TechIndexRoute,
  TechInterventionsIdRoute: TechInterventionsIdRoute,
  TechInterventionsIndexRoute: TechInterventionsIndexRoute,
}

const TechRouteWithChildren = TechRoute._addFileChildren(TechRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  TechRoute: TechRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
